
riot:
  api-key: "RGAPI-9b8586cc-0140-45b9-8ca5-3d7b990bf48e"

logging:
  level:
    root: info

spring:
  datasource:
    connection-init-sql: "SET NAMES utf8mb4"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matcher?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "0000"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect